spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    baselineOnMigrate: true
logging:
  level:
    root: INFO
application:

