spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: employee
    password: postgres
logging:
  level:
    root: INFO
application:

